services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    packages:
      - tesseract-ocr
      - libreoffice
      - poppler-utils
      - libmagic1
      - antiword
      - unrtf
      - imagemagick
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
